using System.CommandLine;
using System.Diagnostics;
using System.Text;
using Engram.Store;

namespace Engram.Cli;

/// <summary>
/// HU-051 (ENG-481): `engram init` — installs git hooks that auto-capture every
/// commit as a searchable memory (<c>type=commit</c>).
///
/// Encapsulates all init logic (git detection, template generation, backup policy,
/// file writing, output formatting) so <c>Program.cs</c> top-level statements stay
/// lean and the logic is testable without shelling out to the compiled binary.
///
/// Shell-safety (NFR-001) and POSIX portability (NFR-003) are enforced by the
/// deterministic template construction: no <c>eval</c>, all runtime expansions
/// double-quoted, embedded values single-quote-escaped at generation time, constant
/// prefixes on positional args, and <c>printf '%s\n'</c> for real newlines.
/// </summary>
public static class GitInitCommand
{
    /// <summary>Marker line written on the first line after the shebang of every generated hook.</summary>
    private const string GeneratedMarker = "# Generated by engram init";

    /// <summary>
    /// Builds the <c>init</c> command with <c>--interactive</c> and <c>--project</c> options.
    /// </summary>
    public static Command CreateCommand()
    {
        var initCmd = new Command("init", "Install git hooks to auto-capture commits as memories");

        var interactiveOpt = new Option<bool>("--interactive")
        {
            Description = "Install interactive prompt (prepare-commit-msg + marker-gated post-commit)",
        };
        var projectOpt = new Option<string?>("--project")
        {
            Description = "Project name to embed (default: auto-detected)",
        };

        initCmd.Options.Add(interactiveOpt);
        initCmd.Options.Add(projectOpt);

        initCmd.SetAction((ParseResult parseResult) =>
        {
            var interactive = parseResult.GetValue(interactiveOpt);
            var cliProject = parseResult.GetValue(projectOpt);
            var cwd = Directory.GetCurrentDirectory();

            // FR-001: resolve git dir (fail-loud if not a repo, nothing written yet)
            string gitDir;
            try
            {
                gitDir = ResolveGitDir(cwd);
            }
            catch (InvalidOperationException ex)
            {
                Console.Error.WriteLine($"error: {ex.Message}");
                return 1;
            }

            // FR-002: resolve + normalize project name, reject unsafe names (fail-loud)
            var projectName = ResolveProjectName(cliProject, cwd);
            if (IsUnsafeProjectName(projectName))
            {
                Console.Error.WriteLine($"error: Project name '{projectName}' contains characters that cannot be safely embedded in a shell script.");
                Console.Error.WriteLine("Use --project <safe-name> to specify an alternative.");
                return 1;
            }

            // G6: resolve binary path (absolute ProcessPath, else PATH fallback)
            var binaryPath = ResolveBinaryPath();

            // FR-002/FR-004: install hooks into <git-dir>/hooks/ (created if missing)
            var hooksDir = Path.Combine(gitDir, "hooks");
            Directory.CreateDirectory(hooksDir);

            bool backedUp;
            try
            {
                if (interactive)
                {
                    backedUp = InstallHook(hooksDir, "post-commit", GeneratePostCommitGated(projectName, binaryPath));
                    backedUp |= InstallHook(hooksDir, "prepare-commit-msg", GeneratePrepareCommitMsg(gitDir));
                }
                else
                {
                    backedUp = InstallHook(hooksDir, "post-commit", GeneratePostCommitAlways(projectName, binaryPath));
                }
            }
            catch (InvalidOperationException ex)
            {
                // FR-006: backup-preexisting fail-loud — nothing was modified
                Console.Error.WriteLine($"error: {ex.Message}");
                return 1;
            }

            // FR-005: adaptive confirmation output
            Console.WriteLine("✓ Git hooks installed:");
            if (interactive)
            {
                Console.WriteLine("  - post-commit (auto-capture with interactive prompt)");
                Console.WriteLine("  - prepare-commit-msg (interactive prompt)");
            }
            else
            {
                Console.WriteLine("  - post-commit (auto-capture every commit)");
            }
            Console.WriteLine($"  Project: {projectName} | engram: {binaryPath}");

            if (binaryPath == "engram")
            {
                Console.WriteLine("  ⚠ engram binary not found at expected path; using PATH fallback.");
                Console.WriteLine("    Set ENGRAM_BIN environment variable in your shell to override.");
            }

            if (backedUp)
            {
                Console.WriteLine("  ⚠ Existing hooks backed up to *.engram-backup");
            }

            if (interactive)
            {
                Console.WriteLine("Disable with: rm .git/hooks/post-commit .git/hooks/prepare-commit-msg");
            }
            else
            {
                Console.WriteLine("Disable with: rm .git/hooks/post-commit");
            }

            return 0;
        });

        return initCmd;
    }

    /// <summary>
    /// Resolves the git dir via `git rev-parse --git-dir` (worktree-safe).
    /// Returns an absolute path.
    /// </summary>
    /// <exception cref="InvalidOperationException">Not a git repository.</exception>
    internal static string ResolveGitDir(string cwd)
    {
        var psi = new ProcessStartInfo
        {
            FileName = "git",
            Arguments = $"-C \"{cwd}\" rev-parse --git-dir",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        using var process = new Process { StartInfo = psi };
        process.Start();
        var output = process.StandardOutput.ReadToEnd().Trim();
        if (!process.WaitForExit(2000))
        {
            try { process.Kill(); } catch { /* best-effort */ }
            throw new InvalidOperationException("Not a git repository. Run 'git init' first.");
        }
        if (process.ExitCode != 0 || string.IsNullOrEmpty(output))
            throw new InvalidOperationException("Not a git repository. Run 'git init' first.");

        return Path.GetFullPath(output, cwd);
    }

    /// <summary>
    /// Project resolution chain: cliProject → ENGRAM_PROJECT → DetectProject → NormalizeProject.
    /// Mirrors the canonical chain in Program.cs (quick-capture).
    /// </summary>
    internal static string ResolveProjectName(string? cliProject, string cwd)
    {
        var storeCfg = StoreConfig.FromEnvironment();
        var project = cliProject
            ?? storeCfg.Project
            ?? ProjectDetector.DetectProject(cwd);
        return Normalizers.NormalizeProject(project);
    }

    /// <summary>
    /// Binary path: <c>Environment.ProcessPath</c> if its file name contains "engram"
    /// (case-insensitive), else the literal <c>"engram"</c> (PATH fallback).
    /// </summary>
    internal static string ResolveBinaryPath()
    {
        var path = Environment.ProcessPath;
        if (path is not null
            && (Path.GetFileName(path) ?? "").Contains("engram", StringComparison.OrdinalIgnoreCase))
        {
            return path;
        }
        return "engram";
    }

    /// <summary>
    /// Returns true if the name contains quote characters that cannot be safely
    /// embedded in a shell script: <c>'</c>, <c>"</c>, <c>`</c>, <c>$</c>.
    /// </summary>
    internal static bool IsUnsafeProjectName(string name)
        => name.Contains('\'') || name.Contains('"') || name.Contains('`') || name.Contains('$');

    /// <summary>POSIX single-quote escape: <c>'</c> → <c>'\''</c>.</summary>
    internal static string EscapeSingleQuote(string value) => value.Replace("'", "'\\''");

    /// <summary>Generates the always-capture post-commit template.</summary>
    internal static string GeneratePostCommitAlways(string projectName, string binaryPath)
    {
        var template =
"""
#!/bin/sh
# Generated by engram init
# Auto-captures every commit as an engram memory.

ENGRAM_BIN="${ENGRAM_BIN:-'<<BINARY>>'}"
PROJECT='<<PROJECT>>'

SUBJECT="$(git log -1 --pretty=%s)"
SHORT_HASH="$(git log -1 --pretty=%h)"
CHANGED_FILES="$(git diff-tree --no-commit-id --name-only -r HEAD)"
FULL_MSG="$(git log -1 --pretty=%B)"

TITLE="commit: ${SUBJECT}"

CONTENT="$(printf '%s\n' "Commit: ${SHORT_HASH}" "Changed files: ${CHANGED_FILES}" "Full message: ${FULL_MSG}")"

"$ENGRAM_BIN" save "$TITLE" "$CONTENT" --type commit --project "$PROJECT" 2>/dev/null || true
""";
        return template
            .Replace("<<BINARY>>", EscapeSingleQuote(binaryPath))
            .Replace("<<PROJECT>>", EscapeSingleQuote(projectName))
            + "\n";
    }

    /// <summary>Generates the marker-gated post-commit template (for <c>--interactive</c>).</summary>
    internal static string GeneratePostCommitGated(string projectName, string binaryPath)
    {
        var template =
"""
#!/bin/sh
# Generated by engram init
# Captures commit as engram memory only if marker exists (interactive consent).

ENGRAM_BIN="${ENGRAM_BIN:-'<<BINARY>>'}"
PROJECT='<<PROJECT>>'
GIT_DIR="$(git rev-parse --git-dir)"
MARKER="${GIT_DIR}/engram-commit-marker"

if [ ! -f "$MARKER" ]; then
    exit 0
fi

SUBJECT="$(git log -1 --pretty=%s)"
SHORT_HASH="$(git log -1 --pretty=%h)"
CHANGED_FILES="$(git diff-tree --no-commit-id --name-only -r HEAD)"
FULL_MSG="$(git log -1 --pretty=%B)"

TITLE="commit: ${SUBJECT}"

CONTENT="$(printf '%s\n' "Commit: ${SHORT_HASH}" "Changed files: ${CHANGED_FILES}" "Full message: ${FULL_MSG}")"

"$ENGRAM_BIN" save "$TITLE" "$CONTENT" --type commit --project "$PROJECT" 2>/dev/null || true

# Consume marker (read + rm)
rm -f "$MARKER"
""";
        return template
            .Replace("<<BINARY>>", EscapeSingleQuote(binaryPath))
            .Replace("<<PROJECT>>", EscapeSingleQuote(projectName))
            + "\n";
    }

    /// <summary>
    /// Generates the prepare-commit-msg template (interactive prompt).
    /// The <paramref name="gitDir"/> is resolved at runtime via <c>git rev-parse --git-dir</c>;
    /// the parameter is kept for API consistency with the other generators.
    /// </summary>
    internal static string GeneratePrepareCommitMsg(string gitDir)
    {
        var template =
"""
#!/bin/sh
# Generated by engram init
# Prompts user for consent to capture commit as engram memory.

GIT_DIR="$(git rev-parse --git-dir)"
MARKER="${GIT_DIR}/engram-commit-marker"
COMMIT_SOURCE="$2"

# Only prompt for empty or message commits
case "$COMMIT_SOURCE" in
    ""|"message") ;;
    *) exit 0 ;;
esac

# TTY guard — no prompt in CI/scripts
if [ ! -t 0 ]; then
    exit 0
fi

printf '¿Guardar este commit como memoria en engram? [Y/n] ' >&2
IFS= read -r REPLY

case "$REPLY" in
    [Yy]|"")
        : > "$MARKER"
        ;;
esac

exit 0
""";
        return template + "\n";
    }

    /// <summary>
    /// Backup policy + write + chmod (FR-006).
    /// Returns true when a foreign hook was backed up (for the output warning).
    /// </summary>
    /// <exception cref="InvalidOperationException">Backup already exists (fail-loud).</exception>
    internal static bool InstallHook(string hooksDir, string hookName, string content)
    {
        var hookPath = Path.Combine(hooksDir, hookName);
        var backupPath = hookPath + ".engram-backup";
        var backedUp = false;

        if (File.Exists(hookPath))
        {
            // Fail-loud before touching anything: never overwrite a prior backup.
            if (File.Exists(backupPath))
                throw new InvalidOperationException(
                    $"Backup {backupPath} already exists. Remove it manually before re-running init.");

            if (IsEngramGenerated(hookPath))
            {
                // engram-generated → replace directly (idempotent, no backup)
            }
            else
            {
                // foreign hook → rename to *.engram-backup
                File.Move(hookPath, backupPath);
                backedUp = true;
            }
        }

        File.WriteAllText(hookPath, content, new UTF8Encoding(false));
        if (OperatingSystem.IsLinux() || OperatingSystem.IsMacOS())
        {
            File.SetUnixFileMode(hookPath,
                UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
        return backedUp;
    }

    /// <summary>
    /// Checks if the first line after the shebang is the engram-generated marker.
    /// </summary>
    internal static bool IsEngramGenerated(string filePath)
    {
        if (!File.Exists(filePath)) return false;
        foreach (var line in File.ReadLines(filePath).Take(3))
        {
            if (line.Trim() == GeneratedMarker) return true;
        }
        return false;
    }
}
